###
GET http://localhost:3000/contacts

### 
GET http://localhost:3000/contacts/63cd7b984d445bc67bf13d18

###  
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
"firstName": "ELENAMARIA",
"lastName": "REBOLLO", 
"email": "TESTING@anything.com",
"FavoriteColor": "PURPLE",
"Birthday": "12/09/2014"
}

### 
PUT http://localhost:3000/contacts/63ccb10109e170c214213060 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Denise",
  "lastName": "Rebollo",
  "Birthday": "03/25/1984",
  "FavoriteColor": "Purple",
  "email": "drebollo09@gmail.com"
}

###
DELETE http://localhost:3000/contacts/63ccb10109e170c214213060 HTTP/1.1



//******************RENDER SITE **********************************************************************

###   GET ALL CONTACTS
GET https://cserebollo.onrender.com/contacts

### GET ONE USER
GET https://cserebollo.onrender.com/contacts/63c1eb80cd316c26b6bcef0d

### POST - CREATE USER
POST https://cserebollo.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
"firstName": "Max",
"lastName": "Rebollo", 
"email": "maxrevoll@anything.com",
"FavoriteColor": "blue",
"Birthday": "12/11/2009"
}

### 
PUT https://cserebollo.onrender.com/contacts/63c1eb80cd316c26b6bcef0d HTTP/1.1
Content-Type: application/json

{
  "firstName": "JSNNN",
  "lastName": "Rebollo",
  "Birthday": "03/25/1984",
  "FavoriteColor": "Purple",
  "email": "drebollo09@gmail.com"
}


### DELETE ONE USER
DELETE https://cserebollo.onrender.com/contacts/63cca948542db7bd2b0695eb