###
GET http://localhost:3000/contacts

### 
GET http://localhost:3000/contacts/63cd7b984d445bc67bf13d18

###  
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
"firstName": "ELENAMARIA",
"lastName": "REBOLLO", 
"FavoriteColor": "PURPLE",
"Birthday": "12/09/2014",
"email": "TESTING@anything.com"
}

### 
PUT http://localhost:3000/contacts/63d60c9917c5626301c98c34 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Max3333",
  "lastName": "Rebollo",
  "Birthday": "09/11/2009",
  "FavoriteColor": "blue",
  "email": "maxrebol@gmail.com"
}

###
DELETE http://localhost:3000/contacts/63ccb10109e170c214213060 HTTP/1.1



//******************RENDER SITE **********************************************************************

###   GET ALL CONTACTS
GET https://cserebollo.onrender.com/contacts

### GET ONE USER
GET https://cserebollo.onrender.com/contacts/63cdbff701c90392d978e42e

### POST - CREATE USER
POST https://cserebollo.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
"firstName": "testing3",
"lastName": "Rebollo", 
"FavoriteColor": "blue",
"Birthday": "12/31/2000",
"email": "sdsdbollo@anything.com"
}

### 
PUT https://cserebollo.onrender.com/contacts/63d5f2c4367fe0bc2713feb3 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Isabella",
  "lastName": "Rebollo",
  "Birthday": "03/25/2003",
  "FavoriteColor": "Purple",
  "email": "isabella@gmail.com"
}


### DELETE ONE USER
DELETE https://cserebollo.onrender.com/contacts/63cdbfb82122b8bb726b23f1